// Code generated by ObjectBox; DO NOT EDIT.

package obx

import (
	"github.com/edgexfoundry/edgex-go/pkg/models"
	. "github.com/edgexfoundry/edgex-go/pkg/models"
	"github.com/google/flatbuffers/go"
	"github.com/objectbox/objectbox-go/objectbox"
	"github.com/objectbox/objectbox-go/objectbox/fbutils"
)

type addressable_EntityInfo struct {
	Id  objectbox.TypeId
	Uid uint64
}

var AddressableBinding = addressable_EntityInfo{
	Id:  1,
	Uid: 7935862170457263125,
}

// Addressable_ contains type-based Property helpers to facilitate some common operations such as Queries.
var Addressable_ = struct {
	Created    *objectbox.PropertyInt64
	Modified   *objectbox.PropertyInt64
	Origin     *objectbox.PropertyInt64
	Id         *objectbox.PropertyUint64
	Name       *objectbox.PropertyString
	Protocol   *objectbox.PropertyString
	HTTPMethod *objectbox.PropertyString
	Address    *objectbox.PropertyString
	Port       *objectbox.PropertyInt
	Path       *objectbox.PropertyString
	Publisher  *objectbox.PropertyString
	User       *objectbox.PropertyString
	Password   *objectbox.PropertyString
	Topic      *objectbox.PropertyString
}{
	Created: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id: 1,
			Entity: &objectbox.Entity{
				Id: 1,
			},
		},
	},
	Modified: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id: 2,
			Entity: &objectbox.Entity{
				Id: 1,
			},
		},
	},
	Origin: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id: 3,
			Entity: &objectbox.Entity{
				Id: 1,
			},
		},
	},
	Id: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id: 4,
			Entity: &objectbox.Entity{
				Id: 1,
			},
		},
	},
	Name: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id: 5,
			Entity: &objectbox.Entity{
				Id: 1,
			},
		},
	},
	Protocol: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id: 6,
			Entity: &objectbox.Entity{
				Id: 1,
			},
		},
	},
	HTTPMethod: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id: 7,
			Entity: &objectbox.Entity{
				Id: 1,
			},
		},
	},
	Address: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id: 8,
			Entity: &objectbox.Entity{
				Id: 1,
			},
		},
	},
	Port: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id: 9,
			Entity: &objectbox.Entity{
				Id: 1,
			},
		},
	},
	Path: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id: 10,
			Entity: &objectbox.Entity{
				Id: 1,
			},
		},
	},
	Publisher: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id: 11,
			Entity: &objectbox.Entity{
				Id: 1,
			},
		},
	},
	User: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id: 12,
			Entity: &objectbox.Entity{
				Id: 1,
			},
		},
	},
	Password: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id: 13,
			Entity: &objectbox.Entity{
				Id: 1,
			},
		},
	},
	Topic: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id: 14,
			Entity: &objectbox.Entity{
				Id: 1,
			},
		},
	},
}

// GeneratorVersion is called by the ObjectBox to verify the compatibility of the generator used to generate this code
func (addressable_EntityInfo) GeneratorVersion() int {
	return 1
}

// AddToModel is called by the ObjectBox during model build
func (addressable_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("Addressable", 1, 7935862170457263125)
	model.Property("Created", objectbox.PropertyType_Long, 1, 3615718190778736815)
	model.Property("Modified", objectbox.PropertyType_Long, 2, 104117847403558709)
	model.Property("Origin", objectbox.PropertyType_Long, 3, 8881371260545183950)
	model.Property("Id", objectbox.PropertyType_Long, 4, 2263870484846289030)
	model.PropertyFlags(objectbox.PropertyFlags_ID)
	model.Property("Name", objectbox.PropertyType_String, 5, 546509660169544040)
	model.PropertyFlags(objectbox.PropertyFlags_UNIQUE)
	model.PropertyIndex(1, 1889048398976443726)
	model.Property("Protocol", objectbox.PropertyType_String, 6, 4418971345113201188)
	model.Property("HTTPMethod", objectbox.PropertyType_String, 7, 1730568939047700080)
	model.Property("Address", objectbox.PropertyType_String, 8, 6145463009686191040)
	model.Property("Port", objectbox.PropertyType_Long, 9, 8050842196399642139)
	model.Property("Path", objectbox.PropertyType_String, 10, 5827872065469493661)
	model.Property("Publisher", objectbox.PropertyType_String, 11, 6793733555422607151)
	model.Property("User", objectbox.PropertyType_String, 12, 6657318061718892543)
	model.Property("Password", objectbox.PropertyType_String, 13, 6306747915668652178)
	model.Property("Topic", objectbox.PropertyType_String, 14, 8483935008079255088)
	model.EntityLastPropertyId(14, 8483935008079255088)
}

// GetId is called by the ObjectBox during Put operations to check for existing ID on an object
func (addressable_EntityInfo) GetId(object interface{}) (uint64, error) {
	if obj, ok := object.(*Addressable); ok {
		return objectbox.StringIdConvertToDatabaseValue(obj.Id), nil
	} else {
		return objectbox.StringIdConvertToDatabaseValue(object.(Addressable).Id), nil
	}
}

// SetId is called by the ObjectBox during Put to update an ID on an object that has just been inserted
func (addressable_EntityInfo) SetId(object interface{}, id uint64) error {
	if obj, ok := object.(*Addressable); ok {
		obj.Id = objectbox.StringIdConvertToEntityProperty(id)
	} else {
		// NOTE while this can't update, it will at least behave consistently (panic in case of a wrong type)
		_ = object.(Addressable).Id
	}
	return nil
}

// Flatten is called by the ObjectBox to transform an object to a FlatBuffer
func (addressable_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) {
	obj := object.(*Addressable)
	var offsetName = fbutils.CreateStringOffset(fbb, obj.Name)
	var offsetProtocol = fbutils.CreateStringOffset(fbb, obj.Protocol)
	var offsetHTTPMethod = fbutils.CreateStringOffset(fbb, obj.HTTPMethod)
	var offsetAddress = fbutils.CreateStringOffset(fbb, obj.Address)
	var offsetPath = fbutils.CreateStringOffset(fbb, obj.Path)
	var offsetPublisher = fbutils.CreateStringOffset(fbb, obj.Publisher)
	var offsetUser = fbutils.CreateStringOffset(fbb, obj.User)
	var offsetPassword = fbutils.CreateStringOffset(fbb, obj.Password)
	var offsetTopic = fbutils.CreateStringOffset(fbb, obj.Topic)

	// build the FlatBuffers object
	fbb.StartObject(14)
	fbutils.SetInt64Slot(fbb, 0, obj.Created)
	fbutils.SetInt64Slot(fbb, 1, obj.Modified)
	fbutils.SetInt64Slot(fbb, 2, obj.Origin)
	fbutils.SetUint64Slot(fbb, 3, id)
	fbutils.SetUOffsetTSlot(fbb, 4, offsetName)
	fbutils.SetUOffsetTSlot(fbb, 5, offsetProtocol)
	fbutils.SetUOffsetTSlot(fbb, 6, offsetHTTPMethod)
	fbutils.SetUOffsetTSlot(fbb, 7, offsetAddress)
	fbutils.SetInt64Slot(fbb, 8, int64(obj.Port))
	fbutils.SetUOffsetTSlot(fbb, 9, offsetPath)
	fbutils.SetUOffsetTSlot(fbb, 10, offsetPublisher)
	fbutils.SetUOffsetTSlot(fbb, 11, offsetUser)
	fbutils.SetUOffsetTSlot(fbb, 12, offsetPassword)
	fbutils.SetUOffsetTSlot(fbb, 13, offsetTopic)
}

// ToObject is called by the ObjectBox to load an object from a FlatBuffer
func (addressable_EntityInfo) ToObject(bytes []byte) interface{} {
	table := &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	return &Addressable{
		BaseObject: models.BaseObject{
			Created:  table.GetInt64Slot(4, 0),
			Modified: table.GetInt64Slot(6, 0),
			Origin:   table.GetInt64Slot(8, 0),
		},
		Id:         objectbox.StringIdConvertToEntityProperty(table.GetUint64Slot(10, 0)),
		Name:       fbutils.GetStringSlot(table, 12),
		Protocol:   fbutils.GetStringSlot(table, 14),
		HTTPMethod: fbutils.GetStringSlot(table, 16),
		Address:    fbutils.GetStringSlot(table, 18),
		Port:       int(table.GetUint64Slot(20, 0)),
		Path:       fbutils.GetStringSlot(table, 22),
		Publisher:  fbutils.GetStringSlot(table, 24),
		User:       fbutils.GetStringSlot(table, 26),
		Password:   fbutils.GetStringSlot(table, 28),
		Topic:      fbutils.GetStringSlot(table, 30),
	}
}

// MakeSlice is called by the ObjectBox to construct a new slice to hold the read objects
func (addressable_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]Addressable, 0, capacity)
}

// AppendToSlice is called by the ObjectBox to fill the slice of the read objects
func (addressable_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	return append(slice.([]Addressable), *object.(*Addressable))
}

// Box provides CRUD access to Addressable objects
type AddressableBox struct {
	*objectbox.Box
}

// BoxForAddressable opens a box of Addressable objects
func BoxForAddressable(ob *objectbox.ObjectBox) *AddressableBox {
	return &AddressableBox{
		Box: ob.InternalBox(1),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the Addressable.Id property on the passed object will be assigned the new ID as well.
func (box *AddressableBox) Put(object *Addressable) (uint64, error) {
	return box.Box.Put(object)
}

// PutAsync asynchronously inserts/updates a single object.
// When inserting, the Addressable.Id property on the passed object will be assigned the new ID as well.
//
// It's executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "Put & Forget:" you gain faster puts as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
//
// In situations with (extremely) high async load, this method may be throttled (~1ms) or delayed (<1s).
// In the unlikely event that the object could not be enqueued after delaying, an error will be returned.
//
// Note that this method does not give you hard durability guarantees like the synchronous Put provides.
// There is a small time window (typically 3 ms) in which the data may not have been committed durably yet.
func (box *AddressableBox) PutAsync(object *Addressable) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutAll inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the Addressable.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the Addressable.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *AddressableBox) PutAll(objects []Addressable) ([]uint64, error) {
	return box.Box.PutAll(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *AddressableBox) Get(id uint64) (*Addressable, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*Addressable), nil
}

// Get reads all stored objects
func (box *AddressableBox) GetAll() ([]Addressable, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]Addressable), nil
}

// Remove deletes a single object
func (box *AddressableBox) Remove(object *Addressable) (err error) {
	return box.Box.Remove(objectbox.StringIdConvertToDatabaseValue(object.Id))
}

// Creates a query with the given conditions. Use the fields of the Addressable_ struct to create conditions.
// Keep the *AddressableQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *AddressableBox) Query(conditions ...objectbox.Condition) *AddressableQuery {
	return &AddressableQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the Addressable_ struct to create conditions.
// Keep the *AddressableQuery if you intend to execute the query multiple times.
func (box *AddressableBox) QueryOrError(conditions ...objectbox.Condition) (*AddressableQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &AddressableQuery{query}, nil
	}
}

// Query provides a way to search stored objects
//
// For example, you can find all Addressable which Id is either 42 or 47:
// 		box.Query(Addressable_.Id.In(42, 47)).Find()
type AddressableQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *AddressableQuery) Find() ([]Addressable, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]Addressable), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *AddressableQuery) Offset(offset uint64) *AddressableQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *AddressableQuery) Limit(limit uint64) *AddressableQuery {
	query.Query.Limit(limit)
	return query
}
