// Code generated by ObjectBox; DO NOT EDIT.
// Learn more about defining entities and generating this file - visit https://golang.objectbox.io/entity-annotations

package obx

import (
	"github.com/edgexfoundry/go-mod-core-contracts/models"
	. "github.com/edgexfoundry/go-mod-core-contracts/models"
	"github.com/google/flatbuffers/go"
	"github.com/objectbox/objectbox-go/objectbox"
	"github.com/objectbox/objectbox-go/objectbox/fbutils"
)

type device_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var DeviceBinding = device_EntityInfo{
	Entity: objectbox.Entity{
		Id: 6,
	},
	Uid: 7791960176883718600,
}

// Device_ contains type-based Property helpers to facilitate some common operations such as Queries.
var Device_ = struct {
	Timestamps_Created  *objectbox.PropertyInt64
	Timestamps_Modified *objectbox.PropertyInt64
	Timestamps_Origin   *objectbox.PropertyInt64
	Description         *objectbox.PropertyString
	Id                  *objectbox.PropertyUint64
	Name                *objectbox.PropertyString
	AdminState          *objectbox.PropertyString
	OperatingState      *objectbox.PropertyString
	Protocols           *objectbox.PropertyByteVector
	LastConnected       *objectbox.PropertyInt64
	LastReported        *objectbox.PropertyInt64
	Labels              *objectbox.PropertyStringVector
	Location            *objectbox.PropertyByteVector
	Service             *objectbox.RelationToOne
	Profile             *objectbox.RelationToOne
	AutoEvents          *objectbox.PropertyByteVector
}{
	Timestamps_Created: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &DeviceBinding.Entity,
		},
	},
	Timestamps_Modified: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &DeviceBinding.Entity,
		},
	},
	Timestamps_Origin: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &DeviceBinding.Entity,
		},
	},
	Description: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     4,
			Entity: &DeviceBinding.Entity,
		},
	},
	Id: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     5,
			Entity: &DeviceBinding.Entity,
		},
	},
	Name: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     6,
			Entity: &DeviceBinding.Entity,
		},
	},
	AdminState: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     7,
			Entity: &DeviceBinding.Entity,
		},
	},
	OperatingState: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     8,
			Entity: &DeviceBinding.Entity,
		},
	},
	Protocols: &objectbox.PropertyByteVector{
		BaseProperty: &objectbox.BaseProperty{
			Id:     9,
			Entity: &DeviceBinding.Entity,
		},
	},
	LastConnected: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     10,
			Entity: &DeviceBinding.Entity,
		},
	},
	LastReported: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     11,
			Entity: &DeviceBinding.Entity,
		},
	},
	Labels: &objectbox.PropertyStringVector{
		BaseProperty: &objectbox.BaseProperty{
			Id:     12,
			Entity: &DeviceBinding.Entity,
		},
	},
	Location: &objectbox.PropertyByteVector{
		BaseProperty: &objectbox.BaseProperty{
			Id:     13,
			Entity: &DeviceBinding.Entity,
		},
	},
	Service: &objectbox.RelationToOne{
		Property: &objectbox.BaseProperty{
			Id:     14,
			Entity: &DeviceBinding.Entity,
		},
		Target: &DeviceServiceBinding.Entity,
	},
	Profile: &objectbox.RelationToOne{
		Property: &objectbox.BaseProperty{
			Id:     15,
			Entity: &DeviceBinding.Entity,
		},
		Target: &DeviceProfileBinding.Entity,
	},
	AutoEvents: &objectbox.PropertyByteVector{
		BaseProperty: &objectbox.BaseProperty{
			Id:     16,
			Entity: &DeviceBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (device_EntityInfo) GeneratorVersion() int {
	return 3
}

// AddToModel is called by ObjectBox during model build
func (device_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("Device", 6, 7791960176883718600)
	model.Property("Timestamps_Created", 6, 1, 760884671802584626)
	model.Property("Timestamps_Modified", 6, 2, 7088417073149650316)
	model.Property("Timestamps_Origin", 6, 3, 5920013286322297706)
	model.Property("Description", 9, 4, 5975955039079730091)
	model.Property("Id", 6, 5, 307498160650160795)
	model.PropertyFlags(8193)
	model.Property("Name", 9, 6, 2954509445996888024)
	model.PropertyFlags(32)
	model.PropertyIndex(5, 8962276722579918082)
	model.Property("AdminState", 9, 7, 6282469246205283102)
	model.Property("OperatingState", 9, 8, 3498097526448157332)
	model.Property("Protocols", 23, 9, 3666750183433369298)
	model.Property("LastConnected", 6, 10, 452571766281036281)
	model.Property("LastReported", 6, 11, 7158543833160973529)
	model.Property("Labels", 30, 12, 7169174010297297034)
	model.Property("Location", 23, 13, 4015086596961837356)
	model.Property("Service", 11, 14, 4088629018495371596)
	model.PropertyFlags(8192)
	model.PropertyRelation("DeviceService", 6, 1605942851186055727)
	model.Property("Profile", 11, 15, 7161954191428807251)
	model.PropertyFlags(8192)
	model.PropertyRelation("DeviceProfile", 7, 1592441353906626817)
	model.Property("AutoEvents", 23, 16, 6886776406948515238)
	model.EntityLastPropertyId(16, 6886776406948515238)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (device_EntityInfo) GetId(object interface{}) (uint64, error) {
	if obj, ok := object.(*Device); ok {
		return objectbox.StringIdConvertToDatabaseValue(obj.Id), nil
	} else {
		return objectbox.StringIdConvertToDatabaseValue(object.(Device).Id), nil
	}
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (device_EntityInfo) SetId(object interface{}, id uint64) {
	if obj, ok := object.(*Device); ok {
		obj.Id = objectbox.StringIdConvertToEntityProperty(id)
	} else {
		// NOTE while this can't update, it will at least behave consistently (panic in case of a wrong type)
		_ = object.(Device).Id
	}
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (device_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	if rel := &object.(*Device).Service; rel != nil {
		if rId, err := DeviceServiceBinding.GetId(rel); err != nil {
			return err
		} else if rId == 0 {
			// NOTE Put/PutAsync() has a side-effect of setting the rel.ID
			if _, err := BoxForDeviceService(ob).Put(rel); err != nil {
				return err
			}
		}
	}
	if rel := &object.(*Device).Profile; rel != nil {
		if rId, err := DeviceProfileBinding.GetId(rel); err != nil {
			return err
		} else if rId == 0 {
			// NOTE Put/PutAsync() has a side-effect of setting the rel.ID
			if _, err := BoxForDeviceProfile(ob).Put(rel); err != nil {
				return err
			}
		}
	}
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (device_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	var obj *Device
	if objPtr, ok := object.(*Device); ok {
		obj = objPtr
	} else {
		objVal := object.(Device)
		obj = &objVal
	}

	var offsetDescription = fbutils.CreateStringOffset(fbb, obj.DescribedObject.Description)
	var offsetName = fbutils.CreateStringOffset(fbb, obj.Name)
	var offsetAdminState = fbutils.CreateStringOffset(fbb, string(obj.AdminState))
	var offsetOperatingState = fbutils.CreateStringOffset(fbb, string(obj.OperatingState))
	var offsetProtocols = fbutils.CreateByteVectorOffset(fbb, mapStringProtocolPropertiesJsonToDatabaseValue(obj.Protocols))
	var offsetLabels = fbutils.CreateStringVectorOffset(fbb, obj.Labels)
	var offsetLocation = fbutils.CreateByteVectorOffset(fbb, interfaceJsonToDatabaseValue(obj.Location))
	var offsetAutoEvents = fbutils.CreateByteVectorOffset(fbb, autoEventsJsonToDatabaseValue(obj.AutoEvents))

	var rIdService uint64
	if rel := &obj.Service; rel != nil {
		if rId, err := DeviceServiceBinding.GetId(rel); err != nil {
			return err
		} else {
			rIdService = rId
		}
	}

	var rIdProfile uint64
	if rel := &obj.Profile; rel != nil {
		if rId, err := DeviceProfileBinding.GetId(rel); err != nil {
			return err
		} else {
			rIdProfile = rId
		}
	}

	// build the FlatBuffers object
	fbb.StartObject(16)
	fbutils.SetInt64Slot(fbb, 0, obj.DescribedObject.Timestamps.Created)
	fbutils.SetInt64Slot(fbb, 1, obj.DescribedObject.Timestamps.Modified)
	fbutils.SetInt64Slot(fbb, 2, obj.DescribedObject.Timestamps.Origin)
	fbutils.SetUOffsetTSlot(fbb, 3, offsetDescription)
	fbutils.SetUint64Slot(fbb, 4, id)
	fbutils.SetUOffsetTSlot(fbb, 5, offsetName)
	fbutils.SetUOffsetTSlot(fbb, 6, offsetAdminState)
	fbutils.SetUOffsetTSlot(fbb, 7, offsetOperatingState)
	fbutils.SetUOffsetTSlot(fbb, 8, offsetProtocols)
	fbutils.SetInt64Slot(fbb, 9, obj.LastConnected)
	fbutils.SetInt64Slot(fbb, 10, obj.LastReported)
	fbutils.SetUOffsetTSlot(fbb, 11, offsetLabels)
	fbutils.SetUOffsetTSlot(fbb, 12, offsetLocation)
	fbutils.SetUint64Slot(fbb, 13, rIdService)
	fbutils.SetUint64Slot(fbb, 14, rIdProfile)
	fbutils.SetUOffsetTSlot(fbb, 15, offsetAutoEvents)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (device_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}
	var id = table.GetUint64Slot(12, 0)

	var relService *DeviceService
	if rId := fbutils.GetUint64Slot(table, 30); rId > 0 {
		if rObject, err := BoxForDeviceService(ob).Get(rId); err != nil {
			return nil, err
		} else {
			relService = rObject
		}
	} else {
		relService = &DeviceService{}
	}

	var relProfile *DeviceProfile
	if rId := fbutils.GetUint64Slot(table, 32); rId > 0 {
		if rObject, err := BoxForDeviceProfile(ob).Get(rId); err != nil {
			return nil, err
		} else {
			relProfile = rObject
		}
	} else {
		relProfile = &DeviceProfile{}
	}

	return &Device{
		DescribedObject: models.DescribedObject{
			Timestamps: Timestamps{
				Created:  fbutils.GetInt64Slot(table, 4),
				Modified: fbutils.GetInt64Slot(table, 6),
				Origin:   fbutils.GetInt64Slot(table, 8),
			},
			Description: fbutils.GetStringSlot(table, 10),
		},
		Id:             objectbox.StringIdConvertToEntityProperty(id),
		Name:           fbutils.GetStringSlot(table, 14),
		AdminState:     models.AdminState(fbutils.GetStringSlot(table, 16)),
		OperatingState: models.OperatingState(fbutils.GetStringSlot(table, 18)),
		Protocols:      mapStringProtocolPropertiesJsonToEntityProperty(fbutils.GetByteVectorSlot(table, 20)),
		LastConnected:  fbutils.GetInt64Slot(table, 22),
		LastReported:   fbutils.GetInt64Slot(table, 24),
		Labels:         fbutils.GetStringVectorSlot(table, 26),
		Location:       interfaceJsonToEntityProperty(fbutils.GetByteVectorSlot(table, 28)),
		Service:        *relService,
		Profile:        *relProfile,
		AutoEvents:     autoEventsJsonToEntityProperty(fbutils.GetByteVectorSlot(table, 34)),
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (device_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]Device, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (device_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	return append(slice.([]Device), *object.(*Device))
}

// Box provides CRUD access to Device objects
type DeviceBox struct {
	*objectbox.Box
}

// BoxForDevice opens a box of Device objects
func BoxForDevice(ob *objectbox.ObjectBox) *DeviceBox {
	return &DeviceBox{
		Box: ob.InternalBox(6),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the Device.Id property on the passed object will be assigned the new ID as well.
func (box *DeviceBox) Put(object *Device) (uint64, error) {
	return box.Box.Put(object)
}

// PutAsync asynchronously inserts/updates a single object.
// When inserting, the Device.Id property on the passed object will be assigned the new ID as well.
//
// It's executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "Put & Forget:" you gain faster puts as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
//
// In situations with (extremely) high async load, this method may be throttled (~1ms) or delayed (<1s).
// In the unlikely event that the object could not be enqueued after delaying, an error will be returned.
//
// Note that this method does not give you hard durability guarantees like the synchronous Put provides.
// There is a small time window (typically 3 ms) in which the data may not have been committed durably yet.
func (box *DeviceBox) PutAsync(object *Device) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the Device.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the Device.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *DeviceBox) PutMany(objects []Device) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *DeviceBox) Get(id uint64) (*Device, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*Device), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is an empty object
func (box *DeviceBox) GetMany(ids ...uint64) ([]Device, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]Device), nil
}

// GetAll reads all stored objects
func (box *DeviceBox) GetAll() ([]Device, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]Device), nil
}

// Remove deletes a single object
func (box *DeviceBox) Remove(object *Device) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *DeviceBox) RemoveMany(objects ...*Device) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = objectbox.StringIdConvertToDatabaseValue(object.Id)
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the Device_ struct to create conditions.
// Keep the *DeviceQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *DeviceBox) Query(conditions ...objectbox.Condition) *DeviceQuery {
	return &DeviceQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the Device_ struct to create conditions.
// Keep the *DeviceQuery if you intend to execute the query multiple times.
func (box *DeviceBox) QueryOrError(conditions ...objectbox.Condition) (*DeviceQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &DeviceQuery{query}, nil
	}
}

// Query provides a way to search stored objects
//
// For example, you can find all Device which Id is either 42 or 47:
// 		box.Query(Device_.Id.In(42, 47)).Find()
type DeviceQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *DeviceQuery) Find() ([]Device, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]Device), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *DeviceQuery) Offset(offset uint64) *DeviceQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *DeviceQuery) Limit(limit uint64) *DeviceQuery {
	query.Query.Limit(limit)
	return query
}
