// Code generated by ObjectBox; DO NOT EDIT.

package obx

import (
	. "github.com/edgexfoundry/edgex-go/pkg/models"
	"github.com/google/flatbuffers/go"
	"github.com/objectbox/objectbox-go/objectbox"
	"github.com/objectbox/objectbox-go/objectbox/fbutils"
)

type interval_EntityInfo struct {
	Id  objectbox.TypeId
	Uid uint64
}

var IntervalBinding = interval_EntityInfo{
	Id:  15,
	Uid: 1843038163747882080,
}

// Interval_ contains type-based Property helpers to facilitate some common operations such as Queries.
var Interval_ = struct {
	ID        *objectbox.PropertyUint64
	Created   *objectbox.PropertyInt64
	Modified  *objectbox.PropertyInt64
	Origin    *objectbox.PropertyInt64
	Name      *objectbox.PropertyString
	Start     *objectbox.PropertyString
	End       *objectbox.PropertyString
	Frequency *objectbox.PropertyString
	Cron      *objectbox.PropertyString
	RunOnce   *objectbox.PropertyBool
}{
	ID: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id: 1,
			Entity: &objectbox.Entity{
				Id: 15,
			},
		},
	},
	Created: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id: 2,
			Entity: &objectbox.Entity{
				Id: 15,
			},
		},
	},
	Modified: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id: 3,
			Entity: &objectbox.Entity{
				Id: 15,
			},
		},
	},
	Origin: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id: 4,
			Entity: &objectbox.Entity{
				Id: 15,
			},
		},
	},
	Name: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id: 5,
			Entity: &objectbox.Entity{
				Id: 15,
			},
		},
	},
	Start: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id: 6,
			Entity: &objectbox.Entity{
				Id: 15,
			},
		},
	},
	End: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id: 7,
			Entity: &objectbox.Entity{
				Id: 15,
			},
		},
	},
	Frequency: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id: 8,
			Entity: &objectbox.Entity{
				Id: 15,
			},
		},
	},
	Cron: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id: 9,
			Entity: &objectbox.Entity{
				Id: 15,
			},
		},
	},
	RunOnce: &objectbox.PropertyBool{
		BaseProperty: &objectbox.BaseProperty{
			Id: 10,
			Entity: &objectbox.Entity{
				Id: 15,
			},
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (interval_EntityInfo) GeneratorVersion() int {
	return 1
}

// AddToModel is called by ObjectBox during model build
func (interval_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("Interval", 15, 1843038163747882080)
	model.Property("ID", objectbox.PropertyType_Long, 1, 7026780808153419659)
	model.PropertyFlags(objectbox.PropertyFlags_ID)
	model.Property("Created", objectbox.PropertyType_Long, 2, 7407031719664088322)
	model.Property("Modified", objectbox.PropertyType_Long, 3, 5313605938834830925)
	model.Property("Origin", objectbox.PropertyType_Long, 4, 2725019847084749631)
	model.Property("Name", objectbox.PropertyType_String, 5, 5958024003810641913)
	model.PropertyFlags(objectbox.PropertyFlags_UNIQUE)
	model.PropertyIndex(19, 1114083913251701929)
	model.Property("Start", objectbox.PropertyType_String, 6, 142790824107722098)
	model.Property("End", objectbox.PropertyType_String, 7, 3265426233578448196)
	model.Property("Frequency", objectbox.PropertyType_String, 8, 2472198800037645616)
	model.Property("Cron", objectbox.PropertyType_String, 9, 6117992782866329900)
	model.Property("RunOnce", objectbox.PropertyType_Bool, 10, 7292712871123113490)
	model.EntityLastPropertyId(10, 7292712871123113490)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (interval_EntityInfo) GetId(object interface{}) (uint64, error) {
	if obj, ok := object.(*Interval); ok {
		return objectbox.StringIdConvertToDatabaseValue(obj.ID), nil
	} else {
		return objectbox.StringIdConvertToDatabaseValue(object.(Interval).ID), nil
	}
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (interval_EntityInfo) SetId(object interface{}, id uint64) {
	if obj, ok := object.(*Interval); ok {
		obj.ID = objectbox.StringIdConvertToEntityProperty(id)
	} else {
		// NOTE while this can't update, it will at least behave consistently (panic in case of a wrong type)
		_ = object.(Interval).ID
	}
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (interval_EntityInfo) PutRelated(txn *objectbox.Transaction, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (interval_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) {
	obj := object.(*Interval)
	var offsetName = fbutils.CreateStringOffset(fbb, obj.Name)
	var offsetStart = fbutils.CreateStringOffset(fbb, obj.Start)
	var offsetEnd = fbutils.CreateStringOffset(fbb, obj.End)
	var offsetFrequency = fbutils.CreateStringOffset(fbb, obj.Frequency)
	var offsetCron = fbutils.CreateStringOffset(fbb, obj.Cron)

	// build the FlatBuffers object
	fbb.StartObject(10)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetInt64Slot(fbb, 1, obj.Created)
	fbutils.SetInt64Slot(fbb, 2, obj.Modified)
	fbutils.SetInt64Slot(fbb, 3, obj.Origin)
	fbutils.SetUOffsetTSlot(fbb, 4, offsetName)
	fbutils.SetUOffsetTSlot(fbb, 5, offsetStart)
	fbutils.SetUOffsetTSlot(fbb, 6, offsetEnd)
	fbutils.SetUOffsetTSlot(fbb, 7, offsetFrequency)
	fbutils.SetUOffsetTSlot(fbb, 8, offsetCron)
	fbutils.SetBoolSlot(fbb, 9, obj.RunOnce)
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (interval_EntityInfo) Load(txn *objectbox.Transaction, bytes []byte) interface{} {
	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}
	var id = table.GetUint64Slot(4, 0)

	return &Interval{
		ID:        objectbox.StringIdConvertToEntityProperty(id),
		Created:   table.GetInt64Slot(6, 0),
		Modified:  table.GetInt64Slot(8, 0),
		Origin:    table.GetInt64Slot(10, 0),
		Name:      fbutils.GetStringSlot(table, 12),
		Start:     fbutils.GetStringSlot(table, 14),
		End:       fbutils.GetStringSlot(table, 16),
		Frequency: fbutils.GetStringSlot(table, 18),
		Cron:      fbutils.GetStringSlot(table, 20),
		RunOnce:   table.GetBoolSlot(22, false),
	}
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (interval_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]Interval, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (interval_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	return append(slice.([]Interval), *object.(*Interval))
}

// Box provides CRUD access to Interval objects
type IntervalBox struct {
	*objectbox.Box
}

// BoxForInterval opens a box of Interval objects
func BoxForInterval(ob *objectbox.ObjectBox) *IntervalBox {
	return &IntervalBox{
		Box: ob.InternalBox(15),
	}
}

// Put synchronously inserts/updates a single object.
// In case the ID is not specified, it would be assigned automatically (auto-increment).
// When inserting, the Interval.ID property on the passed object will be assigned the new ID as well.
func (box *IntervalBox) Put(object *Interval) (uint64, error) {
	return box.Box.Put(object)
}

// PutAsync asynchronously inserts/updates a single object.
// When inserting, the Interval.ID property on the passed object will be assigned the new ID as well.
//
// It's executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "Put & Forget:" you gain faster puts as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
//
// In situations with (extremely) high async load, this method may be throttled (~1ms) or delayed (<1s).
// In the unlikely event that the object could not be enqueued after delaying, an error will be returned.
//
// Note that this method does not give you hard durability guarantees like the synchronous Put provides.
// There is a small time window (typically 3 ms) in which the data may not have been committed durably yet.
func (box *IntervalBox) PutAsync(object *Interval) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutAll inserts multiple objects in single transaction.
// In case IDs are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the Interval.ID property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the Interval.ID assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *IntervalBox) PutAll(objects []Interval) ([]uint64, error) {
	return box.Box.PutAll(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *IntervalBox) Get(id uint64) (*Interval, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*Interval), nil
}

// Get reads all stored objects
func (box *IntervalBox) GetAll() ([]Interval, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]Interval), nil
}

// Remove deletes a single object
func (box *IntervalBox) Remove(object *Interval) (err error) {
	return box.Box.Remove(objectbox.StringIdConvertToDatabaseValue(object.ID))
}

// Creates a query with the given conditions. Use the fields of the Interval_ struct to create conditions.
// Keep the *IntervalQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *IntervalBox) Query(conditions ...objectbox.Condition) *IntervalQuery {
	return &IntervalQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the Interval_ struct to create conditions.
// Keep the *IntervalQuery if you intend to execute the query multiple times.
func (box *IntervalBox) QueryOrError(conditions ...objectbox.Condition) (*IntervalQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &IntervalQuery{query}, nil
	}
}

// Query provides a way to search stored objects
//
// For example, you can find all Interval which ID is either 42 or 47:
// 		box.Query(Interval_.ID.In(42, 47)).Find()
type IntervalQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *IntervalQuery) Find() ([]Interval, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]Interval), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *IntervalQuery) Offset(offset uint64) *IntervalQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *IntervalQuery) Limit(limit uint64) *IntervalQuery {
	query.Query.Limit(limit)
	return query
}
