// Code generated by ObjectBox; DO NOT EDIT.
// Learn more about defining entities and generating this file - visit https://golang.objectbox.io/entity-annotations

package obx

import (
	"errors"
	. "github.com/edgexfoundry/go-mod-core-contracts/models"
	"github.com/google/flatbuffers/go"
	"github.com/objectbox/objectbox-go/objectbox"
	"github.com/objectbox/objectbox-go/objectbox/fbutils"
)

type intervalAction_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var IntervalActionBinding = intervalAction_EntityInfo{
	Entity: objectbox.Entity{
		Id: 9,
	},
	Uid: 1483985685737893447,
}

// IntervalAction_ contains type-based Property helpers to facilitate some common operations such as Queries.
var IntervalAction_ = struct {
	ID         *objectbox.PropertyUint64
	Created    *objectbox.PropertyInt64
	Modified   *objectbox.PropertyInt64
	Origin     *objectbox.PropertyInt64
	Name       *objectbox.PropertyString
	Interval   *objectbox.PropertyString
	Parameters *objectbox.PropertyString
	Target     *objectbox.PropertyString
	Protocol   *objectbox.PropertyString
	HTTPMethod *objectbox.PropertyString
	Address    *objectbox.PropertyString
	Port       *objectbox.PropertyInt
	Path       *objectbox.PropertyString
	Publisher  *objectbox.PropertyString
	User       *objectbox.PropertyString
	Password   *objectbox.PropertyString
	Topic      *objectbox.PropertyString
}{
	ID: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &IntervalActionBinding.Entity,
		},
	},
	Created: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &IntervalActionBinding.Entity,
		},
	},
	Modified: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &IntervalActionBinding.Entity,
		},
	},
	Origin: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     4,
			Entity: &IntervalActionBinding.Entity,
		},
	},
	Name: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     5,
			Entity: &IntervalActionBinding.Entity,
		},
	},
	Interval: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     6,
			Entity: &IntervalActionBinding.Entity,
		},
	},
	Parameters: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     7,
			Entity: &IntervalActionBinding.Entity,
		},
	},
	Target: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     8,
			Entity: &IntervalActionBinding.Entity,
		},
	},
	Protocol: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     9,
			Entity: &IntervalActionBinding.Entity,
		},
	},
	HTTPMethod: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     10,
			Entity: &IntervalActionBinding.Entity,
		},
	},
	Address: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     11,
			Entity: &IntervalActionBinding.Entity,
		},
	},
	Port: &objectbox.PropertyInt{
		BaseProperty: &objectbox.BaseProperty{
			Id:     12,
			Entity: &IntervalActionBinding.Entity,
		},
	},
	Path: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     13,
			Entity: &IntervalActionBinding.Entity,
		},
	},
	Publisher: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     14,
			Entity: &IntervalActionBinding.Entity,
		},
	},
	User: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     15,
			Entity: &IntervalActionBinding.Entity,
		},
	},
	Password: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     16,
			Entity: &IntervalActionBinding.Entity,
		},
	},
	Topic: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     17,
			Entity: &IntervalActionBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (intervalAction_EntityInfo) GeneratorVersion() int {
	return 5
}

// AddToModel is called by ObjectBox during model build
func (intervalAction_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("IntervalAction", 9, 1483985685737893447)
	model.Property("ID", 6, 1, 8106501057259745639)
	model.PropertyFlags(1)
	model.Property("Created", 6, 2, 8606760504517642302)
	model.Property("Modified", 6, 3, 3733003772936789986)
	model.Property("Origin", 6, 4, 3384319087553382585)
	model.Property("Name", 9, 5, 2527365102278053113)
	model.PropertyFlags(32)
	model.PropertyIndex(9, 2495121518887707707)
	model.Property("Interval", 9, 6, 4045769860823082615)
	model.Property("Parameters", 9, 7, 5680942227765053540)
	model.Property("Target", 9, 8, 2616593658161519544)
	model.Property("Protocol", 9, 9, 386210359121663987)
	model.Property("HTTPMethod", 9, 10, 8050126696687748350)
	model.Property("Address", 9, 11, 622602091182081080)
	model.Property("Port", 6, 12, 6884310575262387856)
	model.Property("Path", 9, 13, 2509507802172033733)
	model.Property("Publisher", 9, 14, 8761571734782667491)
	model.Property("User", 9, 15, 7296768215214404882)
	model.Property("Password", 9, 16, 544386887996073797)
	model.Property("Topic", 9, 17, 3569001711987596649)
	model.EntityLastPropertyId(17, 3569001711987596649)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (intervalAction_EntityInfo) GetId(object interface{}) (uint64, error) {
	if obj, ok := object.(*IntervalAction); ok {
		return objectbox.StringIdConvertToDatabaseValue(obj.ID)
	} else {
		return objectbox.StringIdConvertToDatabaseValue(object.(IntervalAction).ID)
	}
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (intervalAction_EntityInfo) SetId(object interface{}, id uint64) error {
	if obj, ok := object.(*IntervalAction); ok {
		var err error
		obj.ID, err = objectbox.StringIdConvertToEntityProperty(id)
		return err
	} else {
		// NOTE while this can't update, it will at least behave consistently (panic in case of a wrong type)
		_ = object.(IntervalAction).ID
		return nil
	}
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (intervalAction_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (intervalAction_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	var obj *IntervalAction
	if objPtr, ok := object.(*IntervalAction); ok {
		obj = objPtr
	} else {
		objVal := object.(IntervalAction)
		obj = &objVal
	}

	var offsetName = fbutils.CreateStringOffset(fbb, obj.Name)
	var offsetInterval = fbutils.CreateStringOffset(fbb, obj.Interval)
	var offsetParameters = fbutils.CreateStringOffset(fbb, obj.Parameters)
	var offsetTarget = fbutils.CreateStringOffset(fbb, obj.Target)
	var offsetProtocol = fbutils.CreateStringOffset(fbb, obj.Protocol)
	var offsetHTTPMethod = fbutils.CreateStringOffset(fbb, obj.HTTPMethod)
	var offsetAddress = fbutils.CreateStringOffset(fbb, obj.Address)
	var offsetPath = fbutils.CreateStringOffset(fbb, obj.Path)
	var offsetPublisher = fbutils.CreateStringOffset(fbb, obj.Publisher)
	var offsetUser = fbutils.CreateStringOffset(fbb, obj.User)
	var offsetPassword = fbutils.CreateStringOffset(fbb, obj.Password)
	var offsetTopic = fbutils.CreateStringOffset(fbb, obj.Topic)

	// build the FlatBuffers object
	fbb.StartObject(17)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetInt64Slot(fbb, 1, obj.Created)
	fbutils.SetInt64Slot(fbb, 2, obj.Modified)
	fbutils.SetInt64Slot(fbb, 3, obj.Origin)
	fbutils.SetUOffsetTSlot(fbb, 4, offsetName)
	fbutils.SetUOffsetTSlot(fbb, 5, offsetInterval)
	fbutils.SetUOffsetTSlot(fbb, 6, offsetParameters)
	fbutils.SetUOffsetTSlot(fbb, 7, offsetTarget)
	fbutils.SetUOffsetTSlot(fbb, 8, offsetProtocol)
	fbutils.SetUOffsetTSlot(fbb, 9, offsetHTTPMethod)
	fbutils.SetUOffsetTSlot(fbb, 10, offsetAddress)
	fbutils.SetInt64Slot(fbb, 11, int64(obj.Port))
	fbutils.SetUOffsetTSlot(fbb, 12, offsetPath)
	fbutils.SetUOffsetTSlot(fbb, 13, offsetPublisher)
	fbutils.SetUOffsetTSlot(fbb, 14, offsetUser)
	fbutils.SetUOffsetTSlot(fbb, 15, offsetPassword)
	fbutils.SetUOffsetTSlot(fbb, 16, offsetTopic)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (intervalAction_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'IntervalAction' - no data received")
	}

	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	propID, err := objectbox.StringIdConvertToEntityProperty(fbutils.GetUint64Slot(table, 4))
	if err != nil {
		return nil, errors.New("converter objectbox.StringIdConvertToEntityProperty() failed on IntervalAction.ID: " + err.Error())
	}

	return &IntervalAction{
		ID:         propID,
		Created:    fbutils.GetInt64Slot(table, 6),
		Modified:   fbutils.GetInt64Slot(table, 8),
		Origin:     fbutils.GetInt64Slot(table, 10),
		Name:       fbutils.GetStringSlot(table, 12),
		Interval:   fbutils.GetStringSlot(table, 14),
		Parameters: fbutils.GetStringSlot(table, 16),
		Target:     fbutils.GetStringSlot(table, 18),
		Protocol:   fbutils.GetStringSlot(table, 20),
		HTTPMethod: fbutils.GetStringSlot(table, 22),
		Address:    fbutils.GetStringSlot(table, 24),
		Port:       fbutils.GetIntSlot(table, 26),
		Path:       fbutils.GetStringSlot(table, 28),
		Publisher:  fbutils.GetStringSlot(table, 30),
		User:       fbutils.GetStringSlot(table, 32),
		Password:   fbutils.GetStringSlot(table, 34),
		Topic:      fbutils.GetStringSlot(table, 36),
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (intervalAction_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]IntervalAction, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (intervalAction_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]IntervalAction), IntervalAction{})
	}
	return append(slice.([]IntervalAction), *object.(*IntervalAction))
}

// Box provides CRUD access to IntervalAction objects
type IntervalActionBox struct {
	*objectbox.Box
}

// BoxForIntervalAction opens a box of IntervalAction objects
func BoxForIntervalAction(ob *objectbox.ObjectBox) *IntervalActionBox {
	return &IntervalActionBox{
		Box: ob.InternalBox(9),
	}
}

// Put synchronously inserts/updates a single object.
// In case the ID is not specified, it would be assigned automatically (auto-increment).
// When inserting, the IntervalAction.ID property on the passed object will be assigned the new ID as well.
func (box *IntervalActionBox) Put(object *IntervalAction) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the ID is not specified, it would be assigned automatically (auto-increment).
// When inserting, the IntervalAction.ID property on the passed object will be assigned the new ID as well.
func (box *IntervalActionBox) Insert(object *IntervalAction) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *IntervalActionBox) Update(object *IntervalAction) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *IntervalActionBox) PutAsync(object *IntervalAction) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case IDs are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the IntervalAction.ID property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the IntervalAction.ID assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *IntervalActionBox) PutMany(objects []IntervalAction) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *IntervalActionBox) Get(id uint64) (*IntervalAction, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*IntervalAction), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is an empty object
func (box *IntervalActionBox) GetMany(ids ...uint64) ([]IntervalAction, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]IntervalAction), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *IntervalActionBox) GetManyExisting(ids ...uint64) ([]IntervalAction, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]IntervalAction), nil
}

// GetAll reads all stored objects
func (box *IntervalActionBox) GetAll() ([]IntervalAction, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]IntervalAction), nil
}

// Remove deletes a single object
func (box *IntervalActionBox) Remove(object *IntervalAction) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *IntervalActionBox) RemoveMany(objects ...*IntervalAction) (uint64, error) {
	var ids = make([]uint64, len(objects))
	var err error
	for k, object := range objects {
		ids[k], err = objectbox.StringIdConvertToDatabaseValue(object.ID)
		if err != nil {
			return 0, errors.New("converter objectbox.StringIdConvertToDatabaseValue() failed on IntervalAction.ID: " + err.Error())
		}
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the IntervalAction_ struct to create conditions.
// Keep the *IntervalActionQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *IntervalActionBox) Query(conditions ...objectbox.Condition) *IntervalActionQuery {
	return &IntervalActionQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the IntervalAction_ struct to create conditions.
// Keep the *IntervalActionQuery if you intend to execute the query multiple times.
func (box *IntervalActionBox) QueryOrError(conditions ...objectbox.Condition) (*IntervalActionQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &IntervalActionQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See IntervalActionAsyncBox for more information.
func (box *IntervalActionBox) Async() *IntervalActionAsyncBox {
	return &IntervalActionAsyncBox{AsyncBox: box.Box.Async()}
}

// IntervalActionAsyncBox provides asynchronous operations on IntervalAction objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type IntervalActionAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForIntervalAction creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use IntervalActionBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForIntervalAction(ob *objectbox.ObjectBox, timeoutMs uint64) *IntervalActionAsyncBox {
	var async, err = objectbox.NewAsyncBox(ob, 9, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 9: %s" + err.Error())
	}
	return &IntervalActionAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the ID property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *IntervalActionAsyncBox) Put(object *IntervalAction) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The ID property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *IntervalActionAsyncBox) Insert(object *IntervalAction) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *IntervalActionAsyncBox) Update(object *IntervalAction) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *IntervalActionAsyncBox) Remove(object *IntervalAction) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all IntervalAction which ID is either 42 or 47:
// 		box.Query(IntervalAction_.ID.In(42, 47)).Find()
type IntervalActionQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *IntervalActionQuery) Find() ([]IntervalAction, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]IntervalAction), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *IntervalActionQuery) Offset(offset uint64) *IntervalActionQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *IntervalActionQuery) Limit(limit uint64) *IntervalActionQuery {
	query.Query.Limit(limit)
	return query
}
