// Code generated by ObjectBox; DO NOT EDIT.

package obx

import (
	"github.com/objectbox/objectbox-go/objectbox"
)

// ObjectBoxModel declares and builds the model from all the entities in the package.
// It is usually used when setting-up ObjectBox as an argument to the Builder.Model() function.
func ObjectBoxModel() *objectbox.Model {
	model := objectbox.NewModel()
	model.GeneratorVersion(1)

	model.RegisterBinding(AddressableBinding)
	model.RegisterBinding(CommandBinding)
	model.RegisterBinding(DeviceServiceBinding)
	model.RegisterBinding(EventBinding)
	model.RegisterBinding(ReadingBinding)
	model.RegisterBinding(ScheduleEventBinding)
	model.RegisterBinding(ValueDescriptorBinding)
	model.RegisterBinding(ScheduleBinding)
	model.LastEntityId(8, 4067349764907139338)
	model.LastIndexId(6, 111805786000826979)
	model.LastRelationId(1, 7766060310030207431)

	return model
}
