// Code generated by ObjectBox; DO NOT EDIT.

package obx

import (
	. "github.com/edgexfoundry/edgex-go/pkg/models"
	"github.com/google/flatbuffers/go"
	"github.com/objectbox/objectbox-go/objectbox"
	"github.com/objectbox/objectbox-go/objectbox/fbutils"
)

type valueDescriptor_EntityInfo struct {
	Id  objectbox.TypeId
	Uid uint64
}

var ValueDescriptorBinding = valueDescriptor_EntityInfo{
	Id:  18,
	Uid: 5270674616764717680,
}

// ValueDescriptor_ contains type-based Property helpers to facilitate some common operations such as Queries.
var ValueDescriptor_ = struct {
	Id           *objectbox.PropertyUint64
	Created      *objectbox.PropertyInt64
	Description  *objectbox.PropertyString
	Modified     *objectbox.PropertyInt64
	Origin       *objectbox.PropertyInt64
	Name         *objectbox.PropertyString
	Min          *objectbox.PropertyByteVector
	Max          *objectbox.PropertyByteVector
	DefaultValue *objectbox.PropertyByteVector
	Type         *objectbox.PropertyString
	UomLabel     *objectbox.PropertyString
	Formatting   *objectbox.PropertyString
	Labels       *objectbox.PropertyStringVector
}{
	Id: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id: 1,
			Entity: &objectbox.Entity{
				Id: 18,
			},
		},
	},
	Created: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id: 2,
			Entity: &objectbox.Entity{
				Id: 18,
			},
		},
	},
	Description: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id: 3,
			Entity: &objectbox.Entity{
				Id: 18,
			},
		},
	},
	Modified: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id: 4,
			Entity: &objectbox.Entity{
				Id: 18,
			},
		},
	},
	Origin: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id: 5,
			Entity: &objectbox.Entity{
				Id: 18,
			},
		},
	},
	Name: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id: 6,
			Entity: &objectbox.Entity{
				Id: 18,
			},
		},
	},
	Min: &objectbox.PropertyByteVector{
		BaseProperty: &objectbox.BaseProperty{
			Id: 7,
			Entity: &objectbox.Entity{
				Id: 18,
			},
		},
	},
	Max: &objectbox.PropertyByteVector{
		BaseProperty: &objectbox.BaseProperty{
			Id: 8,
			Entity: &objectbox.Entity{
				Id: 18,
			},
		},
	},
	DefaultValue: &objectbox.PropertyByteVector{
		BaseProperty: &objectbox.BaseProperty{
			Id: 9,
			Entity: &objectbox.Entity{
				Id: 18,
			},
		},
	},
	Type: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id: 10,
			Entity: &objectbox.Entity{
				Id: 18,
			},
		},
	},
	UomLabel: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id: 11,
			Entity: &objectbox.Entity{
				Id: 18,
			},
		},
	},
	Formatting: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id: 12,
			Entity: &objectbox.Entity{
				Id: 18,
			},
		},
	},
	Labels: &objectbox.PropertyStringVector{
		BaseProperty: &objectbox.BaseProperty{
			Id: 13,
			Entity: &objectbox.Entity{
				Id: 18,
			},
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (valueDescriptor_EntityInfo) GeneratorVersion() int {
	return 1
}

// AddToModel is called by ObjectBox during model build
func (valueDescriptor_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("ValueDescriptor", 18, 5270674616764717680)
	model.Property("Id", objectbox.PropertyType_Long, 1, 4311317278648370440)
	model.PropertyFlags(objectbox.PropertyFlags_ID)
	model.Property("Created", objectbox.PropertyType_Long, 2, 7190112676589905432)
	model.Property("Description", objectbox.PropertyType_String, 3, 3734164508160642969)
	model.Property("Modified", objectbox.PropertyType_Long, 4, 6779033823013881678)
	model.Property("Origin", objectbox.PropertyType_Long, 5, 1458416511237420680)
	model.Property("Name", objectbox.PropertyType_String, 6, 7490331365197419914)
	model.PropertyFlags(objectbox.PropertyFlags_UNIQUE)
	model.PropertyIndex(22, 167306759802683932)
	model.Property("Min", objectbox.PropertyType_ByteVector, 7, 1028026556096721188)
	model.Property("Max", objectbox.PropertyType_ByteVector, 8, 5857314100811027575)
	model.Property("DefaultValue", objectbox.PropertyType_ByteVector, 9, 7078651487541372965)
	model.Property("Type", objectbox.PropertyType_String, 10, 6831000694820449078)
	model.Property("UomLabel", objectbox.PropertyType_String, 11, 3012618130977761530)
	model.Property("Formatting", objectbox.PropertyType_String, 12, 707808711473441838)
	model.Property("Labels", objectbox.PropertyType_StringVector, 13, 6793276923309349137)
	model.EntityLastPropertyId(13, 6793276923309349137)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (valueDescriptor_EntityInfo) GetId(object interface{}) (uint64, error) {
	if obj, ok := object.(*ValueDescriptor); ok {
		return objectbox.StringIdConvertToDatabaseValue(obj.Id), nil
	} else {
		return objectbox.StringIdConvertToDatabaseValue(object.(ValueDescriptor).Id), nil
	}
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (valueDescriptor_EntityInfo) SetId(object interface{}, id uint64) {
	if obj, ok := object.(*ValueDescriptor); ok {
		obj.Id = objectbox.StringIdConvertToEntityProperty(id)
	} else {
		// NOTE while this can't update, it will at least behave consistently (panic in case of a wrong type)
		_ = object.(ValueDescriptor).Id
	}
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (valueDescriptor_EntityInfo) PutRelated(txn *objectbox.Transaction, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (valueDescriptor_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*ValueDescriptor)
	var offsetDescription = fbutils.CreateStringOffset(fbb, obj.Description)
	var offsetName = fbutils.CreateStringOffset(fbb, obj.Name)
	var offsetMin = fbutils.CreateByteVectorOffset(fbb, interfaceJsonToDatabaseValue(obj.Min))
	var offsetMax = fbutils.CreateByteVectorOffset(fbb, interfaceJsonToDatabaseValue(obj.Max))
	var offsetDefaultValue = fbutils.CreateByteVectorOffset(fbb, interfaceJsonToDatabaseValue(obj.DefaultValue))
	var offsetType = fbutils.CreateStringOffset(fbb, obj.Type)
	var offsetUomLabel = fbutils.CreateStringOffset(fbb, obj.UomLabel)
	var offsetFormatting = fbutils.CreateStringOffset(fbb, obj.Formatting)
	var offsetLabels = fbutils.CreateStringVectorOffset(fbb, obj.Labels)

	// build the FlatBuffers object
	fbb.StartObject(13)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetInt64Slot(fbb, 1, obj.Created)
	fbutils.SetUOffsetTSlot(fbb, 2, offsetDescription)
	fbutils.SetInt64Slot(fbb, 3, obj.Modified)
	fbutils.SetInt64Slot(fbb, 4, obj.Origin)
	fbutils.SetUOffsetTSlot(fbb, 5, offsetName)
	fbutils.SetUOffsetTSlot(fbb, 6, offsetMin)
	fbutils.SetUOffsetTSlot(fbb, 7, offsetMax)
	fbutils.SetUOffsetTSlot(fbb, 8, offsetDefaultValue)
	fbutils.SetUOffsetTSlot(fbb, 9, offsetType)
	fbutils.SetUOffsetTSlot(fbb, 10, offsetUomLabel)
	fbutils.SetUOffsetTSlot(fbb, 11, offsetFormatting)
	fbutils.SetUOffsetTSlot(fbb, 12, offsetLabels)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (valueDescriptor_EntityInfo) Load(txn *objectbox.Transaction, bytes []byte) (interface{}, error) {
	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}
	var id = table.GetUint64Slot(4, 0)

	return &ValueDescriptor{
		Id:           objectbox.StringIdConvertToEntityProperty(id),
		Created:      table.GetInt64Slot(6, 0),
		Description:  fbutils.GetStringSlot(table, 8),
		Modified:     table.GetInt64Slot(10, 0),
		Origin:       table.GetInt64Slot(12, 0),
		Name:         fbutils.GetStringSlot(table, 14),
		Min:          interfaceJsonToEntityProperty(fbutils.GetByteVectorSlot(table, 16)),
		Max:          interfaceJsonToEntityProperty(fbutils.GetByteVectorSlot(table, 18)),
		DefaultValue: interfaceJsonToEntityProperty(fbutils.GetByteVectorSlot(table, 20)),
		Type:         fbutils.GetStringSlot(table, 22),
		UomLabel:     fbutils.GetStringSlot(table, 24),
		Formatting:   fbutils.GetStringSlot(table, 26),
		Labels:       fbutils.GetStringVectorSlot(table, 28),
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (valueDescriptor_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]ValueDescriptor, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (valueDescriptor_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	return append(slice.([]ValueDescriptor), *object.(*ValueDescriptor))
}

// Box provides CRUD access to ValueDescriptor objects
type ValueDescriptorBox struct {
	*objectbox.Box
}

// BoxForValueDescriptor opens a box of ValueDescriptor objects
func BoxForValueDescriptor(ob *objectbox.ObjectBox) *ValueDescriptorBox {
	return &ValueDescriptorBox{
		Box: ob.InternalBox(18),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the ValueDescriptor.Id property on the passed object will be assigned the new ID as well.
func (box *ValueDescriptorBox) Put(object *ValueDescriptor) (uint64, error) {
	return box.Box.Put(object)
}

// PutAsync asynchronously inserts/updates a single object.
// When inserting, the ValueDescriptor.Id property on the passed object will be assigned the new ID as well.
//
// It's executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "Put & Forget:" you gain faster puts as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
//
// In situations with (extremely) high async load, this method may be throttled (~1ms) or delayed (<1s).
// In the unlikely event that the object could not be enqueued after delaying, an error will be returned.
//
// Note that this method does not give you hard durability guarantees like the synchronous Put provides.
// There is a small time window (typically 3 ms) in which the data may not have been committed durably yet.
func (box *ValueDescriptorBox) PutAsync(object *ValueDescriptor) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutAll inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the ValueDescriptor.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the ValueDescriptor.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *ValueDescriptorBox) PutAll(objects []ValueDescriptor) ([]uint64, error) {
	return box.Box.PutAll(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *ValueDescriptorBox) Get(id uint64) (*ValueDescriptor, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*ValueDescriptor), nil
}

// Get reads all stored objects
func (box *ValueDescriptorBox) GetAll() ([]ValueDescriptor, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]ValueDescriptor), nil
}

// Remove deletes a single object
func (box *ValueDescriptorBox) Remove(object *ValueDescriptor) (err error) {
	return box.Box.Remove(objectbox.StringIdConvertToDatabaseValue(object.Id))
}

// Creates a query with the given conditions. Use the fields of the ValueDescriptor_ struct to create conditions.
// Keep the *ValueDescriptorQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *ValueDescriptorBox) Query(conditions ...objectbox.Condition) *ValueDescriptorQuery {
	return &ValueDescriptorQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the ValueDescriptor_ struct to create conditions.
// Keep the *ValueDescriptorQuery if you intend to execute the query multiple times.
func (box *ValueDescriptorBox) QueryOrError(conditions ...objectbox.Condition) (*ValueDescriptorQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &ValueDescriptorQuery{query}, nil
	}
}

// Query provides a way to search stored objects
//
// For example, you can find all ValueDescriptor which Id is either 42 or 47:
// 		box.Query(ValueDescriptor_.Id.In(42, 47)).Find()
type ValueDescriptorQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *ValueDescriptorQuery) Find() ([]ValueDescriptor, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]ValueDescriptor), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *ValueDescriptorQuery) Offset(offset uint64) *ValueDescriptorQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *ValueDescriptorQuery) Limit(limit uint64) *ValueDescriptorQuery {
	query.Query.Limit(limit)
	return query
}
