[Writable]
Persistence = 'file'
LogLevel = 'INFO'

[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = '10s'
Host = 'edgex-support-logging'
Port = 48061
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'This is the Support Logging Microservice'
Timeout = 5000

[Registry]
Host = 'edgex-core-consul'
Port = 8500
Type = 'consul'

[Logging]
File = '/edgex/logs/edgex-support-logging.log'
