[Writable]
Persistence = 'file'
LogLevel = 'INFO'

[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = '10s'
Host = 'edgex-support-logging'
Port = 48061
Protocol = 'http'
MaxResultCount = 50000
StartupMsg = 'This is the Support Logging Microservice'
Timeout = 5000

[Registry]
Host = 'edgex-core-consul'
Port = 8500
Type = 'consul'

[Logging]
File = '/edgex/logs/edgex-support-logging.log'

# currently unused but required for clean startup even with Persistence = 'file'
[Databases]
  [Databases.Primary]
  Name = 'logging'
  Type = 'objectbox'

[SecretStore]
Host = 'edgex-vault'
Port = 8200
Path = '/v1/secret/edgex/logging/'
Protocol = 'https'
RootCaCertPath = '/vault/config/pki/EdgeXFoundryCA/EdgeXFoundryCA.pem'
ServerName = 'edgex-vault'
TokenFile = '/vault/config/assets/resp-init.json'
  [SecretStore.Authentication]
  AuthType = 'X-Vault-Token'

[Startup]
Duration = 30
Interval = 1
