[Writable]
LogLevel = 'INFO'

[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = '10s'
Host = 'localhost'
Port = 48081
Protocol = 'http'
MaxResultCount = 50000
StartupMsg = 'This is the EdgeX Core Metadata Microservice'
Timeout = 5000

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Logging]
EnableRemote = false
File = './logs/edgex-core-metadata.log'

[Clients]
  [Clients.Logging]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48061
  [Clients.Notifications]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48060

[Databases]
  [Databases.Primary]
  Name = 'metadata'
  Type = 'objectbox'

[Notifications]
PostDeviceChanges = true
Slug = 'device-change-'
Content = 'Device update: '
Sender = 'core-metadata'
Description = 'Metadata device notice'
Label = 'metadata'

